/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import java.sql.*; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
import Koneksi.koneksi;
/**
 *
 * @author karno
 */
public class Kasir extends javax.swing.JFrame {
private Connection conn = new koneksi().connect(); 
private DefaultTableModel tabmode;
    /**
     * Creates new formKasir
     */
    public Kasir() {
        initComponents();
        kosong(); 
        aktif(); 
        datatable();
    }
    
    protected void aktif () { 
        txtidk.requestFocus(); 
    } 
    protected void kosong() { 
        txtidk.setText(""); 
        txtnmk.setText(""); 
        txttelpk.setText("");
        txtalmk.setText("");
        txtcarik.setText("");
        buttonGroup1.clearSelection();
    }

    protected void datatable() { 
        Object[] Baris ={"ID Kasir", "Nama", "Jenis Kelamin", "No. Telepon", "Agama","Alamat","Password"}; 
            tabmode = new DefaultTableModel (null, Baris); 
            //tablebarang.setModel(tabmode); 
            String cariitem=txtcarik.getText();
            
            try { 
            String sql = "select * from kasir where idkasir like '%"+cariitem+"%' or nmkasir like '%"+cariitem+"%' order by idkasir asc";
            Statement stat = conn.createStatement(); 
            ResultSet hasil = stat.executeQuery(sql); 
            while (hasil.next()) { 
                tabmode.addRow (new Object[]{ 
                    hasil.getString(1), 
                    hasil.getString(2), 
                    hasil.getString(3), 
                    hasil.getString(4), 
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7) 
                }); 
            }
            tblplgnk.setModel(tabmode); 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidk = new javax.swing.JTextField();
        txtnmk = new javax.swing.JTextField();
        rlakik = new javax.swing.JRadioButton();
        rperempuank = new javax.swing.JRadioButton();
        txtagama = new javax.swing.JTextField();
        txttelpk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalmk = new javax.swing.JTextArea();
        txtpw = new javax.swing.JPasswordField();
        bsimpank = new javax.swing.JButton();
        bubahk = new javax.swing.JButton();
        bhapusk = new javax.swing.JButton();
        bbatalk = new javax.swing.JButton();
        bkeluark = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcarik = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblplgnk = new javax.swing.JTable();
        bcarik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Kasir");

        jLabel2.setText("ID Kasir");

        jLabel3.setText("Nama Kasir");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Agama");

        jLabel6.setText("No Telepon");

        jLabel7.setText("Alamat");

        jLabel8.setText("Password");

        rlakik.setText("Laki-Laki");
        rlakik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlakikActionPerformed(evt);
            }
        });

        rperempuank.setText("Perempuan");

        txtalmk.setColumns(20);
        txtalmk.setRows(5);
        jScrollPane1.setViewportView(txtalmk);

        bsimpank.setText("Simpan");
        bsimpank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpankActionPerformed(evt);
            }
        });

        bubahk.setText("Ubah");
        bubahk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahkActionPerformed(evt);
            }
        });

        bhapusk.setText("Hapus");
        bhapusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapuskActionPerformed(evt);
            }
        });

        bbatalk.setText("Batal");
        bbatalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalkActionPerformed(evt);
            }
        });

        bkeluark.setText("Keluar");
        bkeluark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarkActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data Kasir");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblplgnk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgnk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblplgnk);

        bcarik.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcarik, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcarik)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcarik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsimpank)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bubahk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bhapusk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bbatalk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bkeluark))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttelpk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rlakik)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rperempuank))
                                    .addComponent(txtidk)
                                    .addComponent(txtnmk)
                                    .addComponent(txtagama)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1)))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rlakik)
                    .addComponent(rperempuank))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttelpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpank)
                    .addComponent(bubahk)
                    .addComponent(bhapusk)
                    .addComponent(bbatalk)
                    .addComponent(bkeluark))
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rlakikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlakikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlakikActionPerformed

    private void tblplgnkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnkMouseClicked
        int bar = tblplgnk.getSelectedRow(); 
        String a = tabmode.getValueAt(bar, 0).toString(); 
        String b = tabmode.getValueAt(bar, 1).toString(); 
        String c = tabmode.getValueAt(bar, 2).toString(); 
        String d = tabmode.getValueAt(bar, 3).toString(); 
        String e = tabmode.getValueAt(bar, 4).toString(); 
        String f = tabmode.getValueAt(bar, 5).toString(); 
        String g = tabmode.getValueAt(bar, 6).toString(); 
        
        txtidk.setText(a); 
        txtnmk.setText(b); 
        
        if ("Laki-Laki".equals(c)) { 
            rlakik.setSelected(true); 
            } else{ 
            rperempuank.setSelected(true); 
            } 
        txttelpk.setText(d); 
        txtagama.setText(e);
        txtalmk.setText(f);
        txtpw.setText(g);
    }//GEN-LAST:event_tblplgnkMouseClicked

    private void bsimpankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpankActionPerformed
        String jenis = null;
        if (rlakik.isSelected()) {
            jenis = "Laki-Laki";
        }else if (rperempuank.isSelected()) {
            jenis = "Perempuan";
        }
        String sql = "insert into kasir values (?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidk.getText());
            stat.setString(2, txtnmk.getText());
            stat.setString(3, jenis);
            stat.setString(4, txttelpk.getText());
            stat.setString(5, txtagama.getText());
            stat.setString(6, txtalmk.getText());
            stat.setString(7, txtpw.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtidk.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable(); 
    }//GEN-LAST:event_bsimpankActionPerformed

    private void bubahkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahkActionPerformed
        String jenis = null;
        if (rlakik.isSelected()) {
            jenis = "Laki-Laki";
        }else if (rperempuank.isSelected()) {
            jenis = "Perempuan";
        }

        try{
            String sql = "update kasir set nmkasir=?,jenis=?,telepon=?,agama=?,alamat=?,Password=? where idkasir='"+txtidk.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnmk.getText());
            stat.setString(2, jenis);
            stat.setString(3, txttelpk.getText());
            stat.setString(4, txtagama.getText());
            stat.setString(5, txtalmk.getText());
            stat.setString(6, txtpw.getText());


            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtidk.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahkActionPerformed

    private void bhapuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapuskActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql = "delete from kasir where idkasir ='"+txtidk.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtidk.requestFocus();
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapuskActionPerformed

    private void bbatalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalkActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalkActionPerformed

    private void bkeluarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarkActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatalk;
    private javax.swing.JButton bcarik;
    private javax.swing.JButton bhapusk;
    private javax.swing.JButton bkeluark;
    private javax.swing.JButton bsimpank;
    private javax.swing.JButton bubahk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rlakik;
    private javax.swing.JRadioButton rperempuank;
    private javax.swing.JTable tblplgnk;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextArea txtalmk;
    private javax.swing.JTextField txtcarik;
    private javax.swing.JTextField txtidk;
    private javax.swing.JTextField txtnmk;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txttelpk;
    // End of variables declaration//GEN-END:variables
}
